#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace affsbook
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="adsrush")]
	public partial class AffiliatesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTable_Affsbook_Messages2(Table_Affsbook_Messages2 instance);
    partial void UpdateTable_Affsbook_Messages2(Table_Affsbook_Messages2 instance);
    partial void DeleteTable_Affsbook_Messages2(Table_Affsbook_Messages2 instance);
    partial void InsertTable_Affsbook_Affiliate(Table_Affsbook_Affiliate instance);
    partial void UpdateTable_Affsbook_Affiliate(Table_Affsbook_Affiliate instance);
    partial void DeleteTable_Affsbook_Affiliate(Table_Affsbook_Affiliate instance);
    partial void InsertTable_FreelancersBook_Freelancer(Table_FreelancersBook_Freelancer instance);
    partial void UpdateTable_FreelancersBook_Freelancer(Table_FreelancersBook_Freelancer instance);
    partial void DeleteTable_FreelancersBook_Freelancer(Table_FreelancersBook_Freelancer instance);
    #endregion
		
		public AffiliatesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["adsrushConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AffiliatesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AffiliatesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AffiliatesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AffiliatesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Table_Affsbook_Messages2> Table_Affsbook_Messages2s
		{
			get
			{
				return this.GetTable<Table_Affsbook_Messages2>();
			}
		}
		
		public System.Data.Linq.Table<Table_Affsbook_Affiliate> Table_Affsbook_Affiliates
		{
			get
			{
				return this.GetTable<Table_Affsbook_Affiliate>();
			}
		}
		
		public System.Data.Linq.Table<Table_FreelancersBook_Freelancer> Table_FreelancersBook_Freelancers
		{
			get
			{
				return this.GetTable<Table_FreelancersBook_Freelancer>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_Affsbook_Messages2")]
	public partial class Table_Affsbook_Messages2 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<System.DateTime> _date;
		
		private System.Nullable<int> _senderaid;
		
		private System.Nullable<int> _recieveraid;
		
		private string _subject;
		
		private string _body;
		
		private string _senderusername;
		
		private string _recieverusername;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OndateChanging(System.Nullable<System.DateTime> value);
    partial void OndateChanged();
    partial void OnsenderaidChanging(System.Nullable<int> value);
    partial void OnsenderaidChanged();
    partial void OnrecieveraidChanging(System.Nullable<int> value);
    partial void OnrecieveraidChanged();
    partial void OnsubjectChanging(string value);
    partial void OnsubjectChanged();
    partial void OnbodyChanging(string value);
    partial void OnbodyChanged();
    partial void OnsenderusernameChanging(string value);
    partial void OnsenderusernameChanged();
    partial void OnrecieverusernameChanging(string value);
    partial void OnrecieverusernameChanged();
    #endregion
		
		public Table_Affsbook_Messages2()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_senderaid", DbType="Int")]
		public System.Nullable<int> senderaid
		{
			get
			{
				return this._senderaid;
			}
			set
			{
				if ((this._senderaid != value))
				{
					this.OnsenderaidChanging(value);
					this.SendPropertyChanging();
					this._senderaid = value;
					this.SendPropertyChanged("senderaid");
					this.OnsenderaidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_recieveraid", DbType="Int")]
		public System.Nullable<int> recieveraid
		{
			get
			{
				return this._recieveraid;
			}
			set
			{
				if ((this._recieveraid != value))
				{
					this.OnrecieveraidChanging(value);
					this.SendPropertyChanging();
					this._recieveraid = value;
					this.SendPropertyChanged("recieveraid");
					this.OnrecieveraidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subject", DbType="NVarChar(1500)")]
		public string subject
		{
			get
			{
				return this._subject;
			}
			set
			{
				if ((this._subject != value))
				{
					this.OnsubjectChanging(value);
					this.SendPropertyChanging();
					this._subject = value;
					this.SendPropertyChanged("subject");
					this.OnsubjectChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_body", DbType="NVarChar(4000)")]
		public string body
		{
			get
			{
				return this._body;
			}
			set
			{
				if ((this._body != value))
				{
					this.OnbodyChanging(value);
					this.SendPropertyChanging();
					this._body = value;
					this.SendPropertyChanged("body");
					this.OnbodyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_senderusername", DbType="NVarChar(500)")]
		public string senderusername
		{
			get
			{
				return this._senderusername;
			}
			set
			{
				if ((this._senderusername != value))
				{
					this.OnsenderusernameChanging(value);
					this.SendPropertyChanging();
					this._senderusername = value;
					this.SendPropertyChanged("senderusername");
					this.OnsenderusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_recieverusername", DbType="NVarChar(500)")]
		public string recieverusername
		{
			get
			{
				return this._recieverusername;
			}
			set
			{
				if ((this._recieverusername != value))
				{
					this.OnrecieverusernameChanging(value);
					this.SendPropertyChanging();
					this._recieverusername = value;
					this.SendPropertyChanged("recieverusername");
					this.OnrecieverusernameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_Affsbook_Affiliates")]
	public partial class Table_Affsbook_Affiliate : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<System.DateTime> _signupdate;
		
		private System.Nullable<int> _active;
		
		private System.Nullable<int> _suspended;
		
		private System.Nullable<int> _emailconfirmed;
		
		private System.Nullable<int> _identityconfirmed;
		
		private System.Nullable<int> _contactconfirmed;
		
		private System.Nullable<int> _phoneconfirmed;
		
		private System.Nullable<int> _referaid;
		
		private string _referusername;
		
		private string _email;
		
		private string _username;
		
		private string _password;
		
		private string _displayname;
		
		private string _fullname;
		
		private string _gender;
		
		private string _company;
		
		private string _title;
		
		private string _address;
		
		private string _city;
		
		private string _state;
		
		private string _zip;
		
		private string _country;
		
		private string _phone;
		
		private string _facebook;
		
		private string _skype;
		
		private string _whatsapp;
		
		private string _linkedin;
		
		private string _twitter;
		
		private string _youtubeprofile;
		
		private string _profileimage;
		
		private string _profilelink;
		
		private string _websites;
		
		private string _niche1;
		
		private string _niche2;
		
		private string _niche3;
		
		private string _subniche1;
		
		private string _paymentmethod;
		
		private System.Nullable<int> _affiliatesreferred;
		
		private string _education;
		
		private string _languages;
		
		private string _hobbies;
		
		private System.Nullable<int> _aid;
		
		private string _blog;
		
		private string _biography;
		
		private System.Nullable<int> _profileconfirmed;
		
		private string _moreniches;
		
		private string _kind;
		
		private System.Nullable<float> _balance;
		
		private System.Nullable<float> _lastpayout;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnsignupdateChanging(System.Nullable<System.DateTime> value);
    partial void OnsignupdateChanged();
    partial void OnactiveChanging(System.Nullable<int> value);
    partial void OnactiveChanged();
    partial void OnsuspendedChanging(System.Nullable<int> value);
    partial void OnsuspendedChanged();
    partial void OnemailconfirmedChanging(System.Nullable<int> value);
    partial void OnemailconfirmedChanged();
    partial void OnidentityconfirmedChanging(System.Nullable<int> value);
    partial void OnidentityconfirmedChanged();
    partial void OncontactconfirmedChanging(System.Nullable<int> value);
    partial void OncontactconfirmedChanged();
    partial void OnphoneconfirmedChanging(System.Nullable<int> value);
    partial void OnphoneconfirmedChanged();
    partial void OnreferaidChanging(System.Nullable<int> value);
    partial void OnreferaidChanged();
    partial void OnreferusernameChanging(string value);
    partial void OnreferusernameChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OndisplaynameChanging(string value);
    partial void OndisplaynameChanged();
    partial void OnfullnameChanging(string value);
    partial void OnfullnameChanged();
    partial void OngenderChanging(string value);
    partial void OngenderChanged();
    partial void OncompanyChanging(string value);
    partial void OncompanyChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    partial void OncityChanging(string value);
    partial void OncityChanged();
    partial void OnstateChanging(string value);
    partial void OnstateChanged();
    partial void OnzipChanging(string value);
    partial void OnzipChanged();
    partial void OncountryChanging(string value);
    partial void OncountryChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    partial void OnfacebookChanging(string value);
    partial void OnfacebookChanged();
    partial void OnskypeChanging(string value);
    partial void OnskypeChanged();
    partial void OnwhatsappChanging(string value);
    partial void OnwhatsappChanged();
    partial void OnlinkedinChanging(string value);
    partial void OnlinkedinChanged();
    partial void OntwitterChanging(string value);
    partial void OntwitterChanged();
    partial void OnyoutubeprofileChanging(string value);
    partial void OnyoutubeprofileChanged();
    partial void OnprofileimageChanging(string value);
    partial void OnprofileimageChanged();
    partial void OnprofilelinkChanging(string value);
    partial void OnprofilelinkChanged();
    partial void OnwebsitesChanging(string value);
    partial void OnwebsitesChanged();
    partial void Onniche1Changing(string value);
    partial void Onniche1Changed();
    partial void Onniche2Changing(string value);
    partial void Onniche2Changed();
    partial void Onniche3Changing(string value);
    partial void Onniche3Changed();
    partial void Onsubniche1Changing(string value);
    partial void Onsubniche1Changed();
    partial void OnpaymentmethodChanging(string value);
    partial void OnpaymentmethodChanged();
    partial void OnaffiliatesreferredChanging(System.Nullable<int> value);
    partial void OnaffiliatesreferredChanged();
    partial void OneducationChanging(string value);
    partial void OneducationChanged();
    partial void OnlanguagesChanging(string value);
    partial void OnlanguagesChanged();
    partial void OnhobbiesChanging(string value);
    partial void OnhobbiesChanged();
    partial void OnaidChanging(System.Nullable<int> value);
    partial void OnaidChanged();
    partial void OnblogChanging(string value);
    partial void OnblogChanged();
    partial void OnbiographyChanging(string value);
    partial void OnbiographyChanged();
    partial void OnprofileconfirmedChanging(System.Nullable<int> value);
    partial void OnprofileconfirmedChanged();
    partial void OnmorenichesChanging(string value);
    partial void OnmorenichesChanged();
    partial void OnkindChanging(string value);
    partial void OnkindChanged();
    partial void OnbalanceChanging(System.Nullable<float> value);
    partial void OnbalanceChanged();
    partial void OnlastpayoutChanging(System.Nullable<float> value);
    partial void OnlastpayoutChanged();
    #endregion
		
		public Table_Affsbook_Affiliate()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_signupdate", DbType="Date")]
		public System.Nullable<System.DateTime> signupdate
		{
			get
			{
				return this._signupdate;
			}
			set
			{
				if ((this._signupdate != value))
				{
					this.OnsignupdateChanging(value);
					this.SendPropertyChanging();
					this._signupdate = value;
					this.SendPropertyChanged("signupdate");
					this.OnsignupdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_active", DbType="Int")]
		public System.Nullable<int> active
		{
			get
			{
				return this._active;
			}
			set
			{
				if ((this._active != value))
				{
					this.OnactiveChanging(value);
					this.SendPropertyChanging();
					this._active = value;
					this.SendPropertyChanged("active");
					this.OnactiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_suspended", DbType="Int")]
		public System.Nullable<int> suspended
		{
			get
			{
				return this._suspended;
			}
			set
			{
				if ((this._suspended != value))
				{
					this.OnsuspendedChanging(value);
					this.SendPropertyChanging();
					this._suspended = value;
					this.SendPropertyChanged("suspended");
					this.OnsuspendedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emailconfirmed", DbType="Int")]
		public System.Nullable<int> emailconfirmed
		{
			get
			{
				return this._emailconfirmed;
			}
			set
			{
				if ((this._emailconfirmed != value))
				{
					this.OnemailconfirmedChanging(value);
					this.SendPropertyChanging();
					this._emailconfirmed = value;
					this.SendPropertyChanged("emailconfirmed");
					this.OnemailconfirmedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_identityconfirmed", DbType="Int")]
		public System.Nullable<int> identityconfirmed
		{
			get
			{
				return this._identityconfirmed;
			}
			set
			{
				if ((this._identityconfirmed != value))
				{
					this.OnidentityconfirmedChanging(value);
					this.SendPropertyChanging();
					this._identityconfirmed = value;
					this.SendPropertyChanged("identityconfirmed");
					this.OnidentityconfirmedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contactconfirmed", DbType="Int")]
		public System.Nullable<int> contactconfirmed
		{
			get
			{
				return this._contactconfirmed;
			}
			set
			{
				if ((this._contactconfirmed != value))
				{
					this.OncontactconfirmedChanging(value);
					this.SendPropertyChanging();
					this._contactconfirmed = value;
					this.SendPropertyChanged("contactconfirmed");
					this.OncontactconfirmedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phoneconfirmed", DbType="Int")]
		public System.Nullable<int> phoneconfirmed
		{
			get
			{
				return this._phoneconfirmed;
			}
			set
			{
				if ((this._phoneconfirmed != value))
				{
					this.OnphoneconfirmedChanging(value);
					this.SendPropertyChanging();
					this._phoneconfirmed = value;
					this.SendPropertyChanged("phoneconfirmed");
					this.OnphoneconfirmedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_referaid", DbType="Int")]
		public System.Nullable<int> referaid
		{
			get
			{
				return this._referaid;
			}
			set
			{
				if ((this._referaid != value))
				{
					this.OnreferaidChanging(value);
					this.SendPropertyChanging();
					this._referaid = value;
					this.SendPropertyChanged("referaid");
					this.OnreferaidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_referusername", DbType="NVarChar(500)")]
		public string referusername
		{
			get
			{
				return this._referusername;
			}
			set
			{
				if ((this._referusername != value))
				{
					this.OnreferusernameChanging(value);
					this.SendPropertyChanging();
					this._referusername = value;
					this.SendPropertyChanged("referusername");
					this.OnreferusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(500)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(500)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(500)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_displayname", DbType="NVarChar(500)")]
		public string displayname
		{
			get
			{
				return this._displayname;
			}
			set
			{
				if ((this._displayname != value))
				{
					this.OndisplaynameChanging(value);
					this.SendPropertyChanging();
					this._displayname = value;
					this.SendPropertyChanged("displayname");
					this.OndisplaynameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fullname", DbType="NVarChar(500)")]
		public string fullname
		{
			get
			{
				return this._fullname;
			}
			set
			{
				if ((this._fullname != value))
				{
					this.OnfullnameChanging(value);
					this.SendPropertyChanging();
					this._fullname = value;
					this.SendPropertyChanged("fullname");
					this.OnfullnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender", DbType="NVarChar(500)")]
		public string gender
		{
			get
			{
				return this._gender;
			}
			set
			{
				if ((this._gender != value))
				{
					this.OngenderChanging(value);
					this.SendPropertyChanging();
					this._gender = value;
					this.SendPropertyChanged("gender");
					this.OngenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_company", DbType="NVarChar(500)")]
		public string company
		{
			get
			{
				return this._company;
			}
			set
			{
				if ((this._company != value))
				{
					this.OncompanyChanging(value);
					this.SendPropertyChanging();
					this._company = value;
					this.SendPropertyChanged("company");
					this.OncompanyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(500)")]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="NVarChar(1500)")]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this.OnaddressChanging(value);
					this.SendPropertyChanging();
					this._address = value;
					this.SendPropertyChanged("address");
					this.OnaddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="NVarChar(500)")]
		public string city
		{
			get
			{
				return this._city;
			}
			set
			{
				if ((this._city != value))
				{
					this.OncityChanging(value);
					this.SendPropertyChanging();
					this._city = value;
					this.SendPropertyChanged("city");
					this.OncityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state", DbType="NVarChar(500)")]
		public string state
		{
			get
			{
				return this._state;
			}
			set
			{
				if ((this._state != value))
				{
					this.OnstateChanging(value);
					this.SendPropertyChanging();
					this._state = value;
					this.SendPropertyChanged("state");
					this.OnstateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zip", DbType="NVarChar(500)")]
		public string zip
		{
			get
			{
				return this._zip;
			}
			set
			{
				if ((this._zip != value))
				{
					this.OnzipChanging(value);
					this.SendPropertyChanging();
					this._zip = value;
					this.SendPropertyChanged("zip");
					this.OnzipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_country", DbType="NVarChar(500)")]
		public string country
		{
			get
			{
				return this._country;
			}
			set
			{
				if ((this._country != value))
				{
					this.OncountryChanging(value);
					this.SendPropertyChanging();
					this._country = value;
					this.SendPropertyChanged("country");
					this.OncountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="NVarChar(500)")]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this.OnphoneChanging(value);
					this.SendPropertyChanging();
					this._phone = value;
					this.SendPropertyChanged("phone");
					this.OnphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_facebook", DbType="NVarChar(500)")]
		public string facebook
		{
			get
			{
				return this._facebook;
			}
			set
			{
				if ((this._facebook != value))
				{
					this.OnfacebookChanging(value);
					this.SendPropertyChanging();
					this._facebook = value;
					this.SendPropertyChanged("facebook");
					this.OnfacebookChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_skype", DbType="NVarChar(500)")]
		public string skype
		{
			get
			{
				return this._skype;
			}
			set
			{
				if ((this._skype != value))
				{
					this.OnskypeChanging(value);
					this.SendPropertyChanging();
					this._skype = value;
					this.SendPropertyChanged("skype");
					this.OnskypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_whatsapp", DbType="NVarChar(500)")]
		public string whatsapp
		{
			get
			{
				return this._whatsapp;
			}
			set
			{
				if ((this._whatsapp != value))
				{
					this.OnwhatsappChanging(value);
					this.SendPropertyChanging();
					this._whatsapp = value;
					this.SendPropertyChanged("whatsapp");
					this.OnwhatsappChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_linkedin", DbType="NVarChar(500)")]
		public string linkedin
		{
			get
			{
				return this._linkedin;
			}
			set
			{
				if ((this._linkedin != value))
				{
					this.OnlinkedinChanging(value);
					this.SendPropertyChanging();
					this._linkedin = value;
					this.SendPropertyChanged("linkedin");
					this.OnlinkedinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_twitter", DbType="NVarChar(500)")]
		public string twitter
		{
			get
			{
				return this._twitter;
			}
			set
			{
				if ((this._twitter != value))
				{
					this.OntwitterChanging(value);
					this.SendPropertyChanging();
					this._twitter = value;
					this.SendPropertyChanged("twitter");
					this.OntwitterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_youtubeprofile", DbType="NVarChar(500)")]
		public string youtubeprofile
		{
			get
			{
				return this._youtubeprofile;
			}
			set
			{
				if ((this._youtubeprofile != value))
				{
					this.OnyoutubeprofileChanging(value);
					this.SendPropertyChanging();
					this._youtubeprofile = value;
					this.SendPropertyChanged("youtubeprofile");
					this.OnyoutubeprofileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_profileimage", DbType="NVarChar(3500)")]
		public string profileimage
		{
			get
			{
				return this._profileimage;
			}
			set
			{
				if ((this._profileimage != value))
				{
					this.OnprofileimageChanging(value);
					this.SendPropertyChanging();
					this._profileimage = value;
					this.SendPropertyChanged("profileimage");
					this.OnprofileimageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_profilelink", DbType="NVarChar(500)")]
		public string profilelink
		{
			get
			{
				return this._profilelink;
			}
			set
			{
				if ((this._profilelink != value))
				{
					this.OnprofilelinkChanging(value);
					this.SendPropertyChanging();
					this._profilelink = value;
					this.SendPropertyChanged("profilelink");
					this.OnprofilelinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_websites", DbType="NVarChar(2500)")]
		public string websites
		{
			get
			{
				return this._websites;
			}
			set
			{
				if ((this._websites != value))
				{
					this.OnwebsitesChanging(value);
					this.SendPropertyChanging();
					this._websites = value;
					this.SendPropertyChanged("websites");
					this.OnwebsitesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_niche1", DbType="NVarChar(500)")]
		public string niche1
		{
			get
			{
				return this._niche1;
			}
			set
			{
				if ((this._niche1 != value))
				{
					this.Onniche1Changing(value);
					this.SendPropertyChanging();
					this._niche1 = value;
					this.SendPropertyChanged("niche1");
					this.Onniche1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_niche2", DbType="NVarChar(500)")]
		public string niche2
		{
			get
			{
				return this._niche2;
			}
			set
			{
				if ((this._niche2 != value))
				{
					this.Onniche2Changing(value);
					this.SendPropertyChanging();
					this._niche2 = value;
					this.SendPropertyChanged("niche2");
					this.Onniche2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_niche3", DbType="NVarChar(500)")]
		public string niche3
		{
			get
			{
				return this._niche3;
			}
			set
			{
				if ((this._niche3 != value))
				{
					this.Onniche3Changing(value);
					this.SendPropertyChanging();
					this._niche3 = value;
					this.SendPropertyChanged("niche3");
					this.Onniche3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subniche1", DbType="NVarChar(500)")]
		public string subniche1
		{
			get
			{
				return this._subniche1;
			}
			set
			{
				if ((this._subniche1 != value))
				{
					this.Onsubniche1Changing(value);
					this.SendPropertyChanging();
					this._subniche1 = value;
					this.SendPropertyChanged("subniche1");
					this.Onsubniche1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paymentmethod", DbType="NVarChar(500)")]
		public string paymentmethod
		{
			get
			{
				return this._paymentmethod;
			}
			set
			{
				if ((this._paymentmethod != value))
				{
					this.OnpaymentmethodChanging(value);
					this.SendPropertyChanging();
					this._paymentmethod = value;
					this.SendPropertyChanged("paymentmethod");
					this.OnpaymentmethodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_affiliatesreferred", DbType="Int")]
		public System.Nullable<int> affiliatesreferred
		{
			get
			{
				return this._affiliatesreferred;
			}
			set
			{
				if ((this._affiliatesreferred != value))
				{
					this.OnaffiliatesreferredChanging(value);
					this.SendPropertyChanging();
					this._affiliatesreferred = value;
					this.SendPropertyChanged("affiliatesreferred");
					this.OnaffiliatesreferredChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_education", DbType="NVarChar(500)")]
		public string education
		{
			get
			{
				return this._education;
			}
			set
			{
				if ((this._education != value))
				{
					this.OneducationChanging(value);
					this.SendPropertyChanging();
					this._education = value;
					this.SendPropertyChanged("education");
					this.OneducationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_languages", DbType="NVarChar(500)")]
		public string languages
		{
			get
			{
				return this._languages;
			}
			set
			{
				if ((this._languages != value))
				{
					this.OnlanguagesChanging(value);
					this.SendPropertyChanging();
					this._languages = value;
					this.SendPropertyChanged("languages");
					this.OnlanguagesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hobbies", DbType="NVarChar(500)")]
		public string hobbies
		{
			get
			{
				return this._hobbies;
			}
			set
			{
				if ((this._hobbies != value))
				{
					this.OnhobbiesChanging(value);
					this.SendPropertyChanging();
					this._hobbies = value;
					this.SendPropertyChanged("hobbies");
					this.OnhobbiesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aid", DbType="Int")]
		public System.Nullable<int> aid
		{
			get
			{
				return this._aid;
			}
			set
			{
				if ((this._aid != value))
				{
					this.OnaidChanging(value);
					this.SendPropertyChanging();
					this._aid = value;
					this.SendPropertyChanged("aid");
					this.OnaidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_blog", DbType="NVarChar(500)")]
		public string blog
		{
			get
			{
				return this._blog;
			}
			set
			{
				if ((this._blog != value))
				{
					this.OnblogChanging(value);
					this.SendPropertyChanging();
					this._blog = value;
					this.SendPropertyChanged("blog");
					this.OnblogChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_biography", DbType="NVarChar(2500)")]
		public string biography
		{
			get
			{
				return this._biography;
			}
			set
			{
				if ((this._biography != value))
				{
					this.OnbiographyChanging(value);
					this.SendPropertyChanging();
					this._biography = value;
					this.SendPropertyChanged("biography");
					this.OnbiographyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_profileconfirmed", DbType="Int")]
		public System.Nullable<int> profileconfirmed
		{
			get
			{
				return this._profileconfirmed;
			}
			set
			{
				if ((this._profileconfirmed != value))
				{
					this.OnprofileconfirmedChanging(value);
					this.SendPropertyChanging();
					this._profileconfirmed = value;
					this.SendPropertyChanged("profileconfirmed");
					this.OnprofileconfirmedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_moreniches", DbType="NVarChar(2500)")]
		public string moreniches
		{
			get
			{
				return this._moreniches;
			}
			set
			{
				if ((this._moreniches != value))
				{
					this.OnmorenichesChanging(value);
					this.SendPropertyChanging();
					this._moreniches = value;
					this.SendPropertyChanged("moreniches");
					this.OnmorenichesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kind", DbType="NVarChar(500)")]
		public string kind
		{
			get
			{
				return this._kind;
			}
			set
			{
				if ((this._kind != value))
				{
					this.OnkindChanging(value);
					this.SendPropertyChanging();
					this._kind = value;
					this.SendPropertyChanged("kind");
					this.OnkindChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_balance", DbType="Real")]
		public System.Nullable<float> balance
		{
			get
			{
				return this._balance;
			}
			set
			{
				if ((this._balance != value))
				{
					this.OnbalanceChanging(value);
					this.SendPropertyChanging();
					this._balance = value;
					this.SendPropertyChanged("balance");
					this.OnbalanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastpayout", DbType="Real")]
		public System.Nullable<float> lastpayout
		{
			get
			{
				return this._lastpayout;
			}
			set
			{
				if ((this._lastpayout != value))
				{
					this.OnlastpayoutChanging(value);
					this.SendPropertyChanging();
					this._lastpayout = value;
					this.SendPropertyChanged("lastpayout");
					this.OnlastpayoutChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_FreelancersBook_Freelancers")]
	public partial class Table_FreelancersBook_Freelancer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<System.DateTime> _signupdate;
		
		private System.Nullable<int> _aid;
		
		private System.Nullable<int> _active;
		
		private System.Nullable<int> _suspended;
		
		private System.Nullable<int> _emailconfirmed;
		
		private System.Nullable<int> _identityconfirmed;
		
		private System.Nullable<int> _contactconfirmed;
		
		private System.Nullable<int> _phoneconfirmed;
		
		private System.Nullable<int> _referaid;
		
		private string _referusername;
		
		private string _email;
		
		private string _username;
		
		private string _password;
		
		private string _fullname;
		
		private string _gender;
		
		private string _city;
		
		private string _country;
		
		private string _experience;
		
		private string _skype;
		
		private string _facebook;
		
		private string _linkedin;
		
		private string _whatsapp;
		
		private string _profileimage;
		
		private string _website;
		
		private string _category;
		
		private string _subcategory;
		
		private string _paymentmethod;
		
		private System.Nullable<float> _balance;
		
		private System.Nullable<float> _lastpayout;
		
		private System.Nullable<System.DateTime> _lastpayoutdate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnsignupdateChanging(System.Nullable<System.DateTime> value);
    partial void OnsignupdateChanged();
    partial void OnaidChanging(System.Nullable<int> value);
    partial void OnaidChanged();
    partial void OnactiveChanging(System.Nullable<int> value);
    partial void OnactiveChanged();
    partial void OnsuspendedChanging(System.Nullable<int> value);
    partial void OnsuspendedChanged();
    partial void OnemailconfirmedChanging(System.Nullable<int> value);
    partial void OnemailconfirmedChanged();
    partial void OnidentityconfirmedChanging(System.Nullable<int> value);
    partial void OnidentityconfirmedChanged();
    partial void OncontactconfirmedChanging(System.Nullable<int> value);
    partial void OncontactconfirmedChanged();
    partial void OnphoneconfirmedChanging(System.Nullable<int> value);
    partial void OnphoneconfirmedChanged();
    partial void OnreferaidChanging(System.Nullable<int> value);
    partial void OnreferaidChanged();
    partial void OnreferusernameChanging(string value);
    partial void OnreferusernameChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnfullnameChanging(string value);
    partial void OnfullnameChanged();
    partial void OngenderChanging(string value);
    partial void OngenderChanged();
    partial void OncityChanging(string value);
    partial void OncityChanged();
    partial void OncountryChanging(string value);
    partial void OncountryChanged();
    partial void OnexperienceChanging(string value);
    partial void OnexperienceChanged();
    partial void OnskypeChanging(string value);
    partial void OnskypeChanged();
    partial void OnfacebookChanging(string value);
    partial void OnfacebookChanged();
    partial void OnlinkedinChanging(string value);
    partial void OnlinkedinChanged();
    partial void OnwhatsappChanging(string value);
    partial void OnwhatsappChanged();
    partial void OnprofileimageChanging(string value);
    partial void OnprofileimageChanged();
    partial void OnwebsiteChanging(string value);
    partial void OnwebsiteChanged();
    partial void OncategoryChanging(string value);
    partial void OncategoryChanged();
    partial void OnsubcategoryChanging(string value);
    partial void OnsubcategoryChanged();
    partial void OnpaymentmethodChanging(string value);
    partial void OnpaymentmethodChanged();
    partial void OnbalanceChanging(System.Nullable<float> value);
    partial void OnbalanceChanged();
    partial void OnlastpayoutChanging(System.Nullable<float> value);
    partial void OnlastpayoutChanged();
    partial void OnlastpayoutdateChanging(System.Nullable<System.DateTime> value);
    partial void OnlastpayoutdateChanged();
    #endregion
		
		public Table_FreelancersBook_Freelancer()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_signupdate", DbType="Date")]
		public System.Nullable<System.DateTime> signupdate
		{
			get
			{
				return this._signupdate;
			}
			set
			{
				if ((this._signupdate != value))
				{
					this.OnsignupdateChanging(value);
					this.SendPropertyChanging();
					this._signupdate = value;
					this.SendPropertyChanged("signupdate");
					this.OnsignupdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aid", DbType="Int")]
		public System.Nullable<int> aid
		{
			get
			{
				return this._aid;
			}
			set
			{
				if ((this._aid != value))
				{
					this.OnaidChanging(value);
					this.SendPropertyChanging();
					this._aid = value;
					this.SendPropertyChanged("aid");
					this.OnaidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_active", DbType="Int")]
		public System.Nullable<int> active
		{
			get
			{
				return this._active;
			}
			set
			{
				if ((this._active != value))
				{
					this.OnactiveChanging(value);
					this.SendPropertyChanging();
					this._active = value;
					this.SendPropertyChanged("active");
					this.OnactiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_suspended", DbType="Int")]
		public System.Nullable<int> suspended
		{
			get
			{
				return this._suspended;
			}
			set
			{
				if ((this._suspended != value))
				{
					this.OnsuspendedChanging(value);
					this.SendPropertyChanging();
					this._suspended = value;
					this.SendPropertyChanged("suspended");
					this.OnsuspendedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emailconfirmed", DbType="Int")]
		public System.Nullable<int> emailconfirmed
		{
			get
			{
				return this._emailconfirmed;
			}
			set
			{
				if ((this._emailconfirmed != value))
				{
					this.OnemailconfirmedChanging(value);
					this.SendPropertyChanging();
					this._emailconfirmed = value;
					this.SendPropertyChanged("emailconfirmed");
					this.OnemailconfirmedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_identityconfirmed", DbType="Int")]
		public System.Nullable<int> identityconfirmed
		{
			get
			{
				return this._identityconfirmed;
			}
			set
			{
				if ((this._identityconfirmed != value))
				{
					this.OnidentityconfirmedChanging(value);
					this.SendPropertyChanging();
					this._identityconfirmed = value;
					this.SendPropertyChanged("identityconfirmed");
					this.OnidentityconfirmedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contactconfirmed", DbType="Int")]
		public System.Nullable<int> contactconfirmed
		{
			get
			{
				return this._contactconfirmed;
			}
			set
			{
				if ((this._contactconfirmed != value))
				{
					this.OncontactconfirmedChanging(value);
					this.SendPropertyChanging();
					this._contactconfirmed = value;
					this.SendPropertyChanged("contactconfirmed");
					this.OncontactconfirmedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phoneconfirmed", DbType="Int")]
		public System.Nullable<int> phoneconfirmed
		{
			get
			{
				return this._phoneconfirmed;
			}
			set
			{
				if ((this._phoneconfirmed != value))
				{
					this.OnphoneconfirmedChanging(value);
					this.SendPropertyChanging();
					this._phoneconfirmed = value;
					this.SendPropertyChanged("phoneconfirmed");
					this.OnphoneconfirmedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_referaid", DbType="Int")]
		public System.Nullable<int> referaid
		{
			get
			{
				return this._referaid;
			}
			set
			{
				if ((this._referaid != value))
				{
					this.OnreferaidChanging(value);
					this.SendPropertyChanging();
					this._referaid = value;
					this.SendPropertyChanged("referaid");
					this.OnreferaidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_referusername", DbType="NVarChar(2000)")]
		public string referusername
		{
			get
			{
				return this._referusername;
			}
			set
			{
				if ((this._referusername != value))
				{
					this.OnreferusernameChanging(value);
					this.SendPropertyChanging();
					this._referusername = value;
					this.SendPropertyChanged("referusername");
					this.OnreferusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(1500)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(1500)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(1500)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fullname", DbType="NVarChar(1500)")]
		public string fullname
		{
			get
			{
				return this._fullname;
			}
			set
			{
				if ((this._fullname != value))
				{
					this.OnfullnameChanging(value);
					this.SendPropertyChanging();
					this._fullname = value;
					this.SendPropertyChanged("fullname");
					this.OnfullnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender", DbType="NVarChar(1500)")]
		public string gender
		{
			get
			{
				return this._gender;
			}
			set
			{
				if ((this._gender != value))
				{
					this.OngenderChanging(value);
					this.SendPropertyChanging();
					this._gender = value;
					this.SendPropertyChanged("gender");
					this.OngenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="NVarChar(1500)")]
		public string city
		{
			get
			{
				return this._city;
			}
			set
			{
				if ((this._city != value))
				{
					this.OncityChanging(value);
					this.SendPropertyChanging();
					this._city = value;
					this.SendPropertyChanged("city");
					this.OncityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_country", DbType="NVarChar(1500)")]
		public string country
		{
			get
			{
				return this._country;
			}
			set
			{
				if ((this._country != value))
				{
					this.OncountryChanging(value);
					this.SendPropertyChanging();
					this._country = value;
					this.SendPropertyChanged("country");
					this.OncountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_experience", DbType="NVarChar(3500)")]
		public string experience
		{
			get
			{
				return this._experience;
			}
			set
			{
				if ((this._experience != value))
				{
					this.OnexperienceChanging(value);
					this.SendPropertyChanging();
					this._experience = value;
					this.SendPropertyChanged("experience");
					this.OnexperienceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_skype", DbType="NVarChar(1500)")]
		public string skype
		{
			get
			{
				return this._skype;
			}
			set
			{
				if ((this._skype != value))
				{
					this.OnskypeChanging(value);
					this.SendPropertyChanging();
					this._skype = value;
					this.SendPropertyChanged("skype");
					this.OnskypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_facebook", DbType="NVarChar(1500)")]
		public string facebook
		{
			get
			{
				return this._facebook;
			}
			set
			{
				if ((this._facebook != value))
				{
					this.OnfacebookChanging(value);
					this.SendPropertyChanging();
					this._facebook = value;
					this.SendPropertyChanged("facebook");
					this.OnfacebookChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_linkedin", DbType="NVarChar(1500)")]
		public string linkedin
		{
			get
			{
				return this._linkedin;
			}
			set
			{
				if ((this._linkedin != value))
				{
					this.OnlinkedinChanging(value);
					this.SendPropertyChanging();
					this._linkedin = value;
					this.SendPropertyChanged("linkedin");
					this.OnlinkedinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_whatsapp", DbType="NVarChar(1500)")]
		public string whatsapp
		{
			get
			{
				return this._whatsapp;
			}
			set
			{
				if ((this._whatsapp != value))
				{
					this.OnwhatsappChanging(value);
					this.SendPropertyChanging();
					this._whatsapp = value;
					this.SendPropertyChanged("whatsapp");
					this.OnwhatsappChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_profileimage", DbType="NVarChar(3500)")]
		public string profileimage
		{
			get
			{
				return this._profileimage;
			}
			set
			{
				if ((this._profileimage != value))
				{
					this.OnprofileimageChanging(value);
					this.SendPropertyChanging();
					this._profileimage = value;
					this.SendPropertyChanged("profileimage");
					this.OnprofileimageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_website", DbType="NVarChar(3500)")]
		public string website
		{
			get
			{
				return this._website;
			}
			set
			{
				if ((this._website != value))
				{
					this.OnwebsiteChanging(value);
					this.SendPropertyChanging();
					this._website = value;
					this.SendPropertyChanged("website");
					this.OnwebsiteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category", DbType="NVarChar(1500)")]
		public string category
		{
			get
			{
				return this._category;
			}
			set
			{
				if ((this._category != value))
				{
					this.OncategoryChanging(value);
					this.SendPropertyChanging();
					this._category = value;
					this.SendPropertyChanged("category");
					this.OncategoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subcategory", DbType="NVarChar(1500)")]
		public string subcategory
		{
			get
			{
				return this._subcategory;
			}
			set
			{
				if ((this._subcategory != value))
				{
					this.OnsubcategoryChanging(value);
					this.SendPropertyChanging();
					this._subcategory = value;
					this.SendPropertyChanged("subcategory");
					this.OnsubcategoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paymentmethod", DbType="NVarChar(1500)")]
		public string paymentmethod
		{
			get
			{
				return this._paymentmethod;
			}
			set
			{
				if ((this._paymentmethod != value))
				{
					this.OnpaymentmethodChanging(value);
					this.SendPropertyChanging();
					this._paymentmethod = value;
					this.SendPropertyChanged("paymentmethod");
					this.OnpaymentmethodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_balance", DbType="Real")]
		public System.Nullable<float> balance
		{
			get
			{
				return this._balance;
			}
			set
			{
				if ((this._balance != value))
				{
					this.OnbalanceChanging(value);
					this.SendPropertyChanging();
					this._balance = value;
					this.SendPropertyChanged("balance");
					this.OnbalanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastpayout", DbType="Real")]
		public System.Nullable<float> lastpayout
		{
			get
			{
				return this._lastpayout;
			}
			set
			{
				if ((this._lastpayout != value))
				{
					this.OnlastpayoutChanging(value);
					this.SendPropertyChanging();
					this._lastpayout = value;
					this.SendPropertyChanged("lastpayout");
					this.OnlastpayoutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastpayoutdate", DbType="Date")]
		public System.Nullable<System.DateTime> lastpayoutdate
		{
			get
			{
				return this._lastpayoutdate;
			}
			set
			{
				if ((this._lastpayoutdate != value))
				{
					this.OnlastpayoutdateChanging(value);
					this.SendPropertyChanging();
					this._lastpayoutdate = value;
					this.SendPropertyChanged("lastpayoutdate");
					this.OnlastpayoutdateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
