#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace affsbook
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="adsrush")]
	public partial class cashDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTable_Affsbook_AffStat(Table_Affsbook_AffStat instance);
    partial void UpdateTable_Affsbook_AffStat(Table_Affsbook_AffStat instance);
    partial void DeleteTable_Affsbook_AffStat(Table_Affsbook_AffStat instance);
    #endregion
		
		public cashDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["adsrushConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public cashDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public cashDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public cashDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public cashDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Table_Affsbook_AffStat> Table_Affsbook_AffStats
		{
			get
			{
				return this.GetTable<Table_Affsbook_AffStat>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_Affsbook_AffStats")]
	public partial class Table_Affsbook_AffStat : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<System.DateTime> _date;
		
		private System.Nullable<int> _aid;
		
		private string _username;
		
		private System.Nullable<int> _affreferred;
		
		private System.Nullable<int> _pubreferred;
		
		private System.Nullable<float> _revenues;
		
		private System.Nullable<float> _earnings;
		
		private System.Nullable<int> _month;
		
		private System.Nullable<int> _year;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OndateChanging(System.Nullable<System.DateTime> value);
    partial void OndateChanged();
    partial void OnaidChanging(System.Nullable<int> value);
    partial void OnaidChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnaffreferredChanging(System.Nullable<int> value);
    partial void OnaffreferredChanged();
    partial void OnpubreferredChanging(System.Nullable<int> value);
    partial void OnpubreferredChanged();
    partial void OnrevenuesChanging(System.Nullable<float> value);
    partial void OnrevenuesChanged();
    partial void OnearningsChanging(System.Nullable<float> value);
    partial void OnearningsChanged();
    partial void OnmonthChanging(System.Nullable<int> value);
    partial void OnmonthChanged();
    partial void OnyearChanging(System.Nullable<int> value);
    partial void OnyearChanged();
    #endregion
		
		public Table_Affsbook_AffStat()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aid", DbType="Int")]
		public System.Nullable<int> aid
		{
			get
			{
				return this._aid;
			}
			set
			{
				if ((this._aid != value))
				{
					this.OnaidChanging(value);
					this.SendPropertyChanging();
					this._aid = value;
					this.SendPropertyChanged("aid");
					this.OnaidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(500)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_affreferred", DbType="Int")]
		public System.Nullable<int> affreferred
		{
			get
			{
				return this._affreferred;
			}
			set
			{
				if ((this._affreferred != value))
				{
					this.OnaffreferredChanging(value);
					this.SendPropertyChanging();
					this._affreferred = value;
					this.SendPropertyChanged("affreferred");
					this.OnaffreferredChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pubreferred", DbType="Int")]
		public System.Nullable<int> pubreferred
		{
			get
			{
				return this._pubreferred;
			}
			set
			{
				if ((this._pubreferred != value))
				{
					this.OnpubreferredChanging(value);
					this.SendPropertyChanging();
					this._pubreferred = value;
					this.SendPropertyChanged("pubreferred");
					this.OnpubreferredChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_revenues", DbType="Real")]
		public System.Nullable<float> revenues
		{
			get
			{
				return this._revenues;
			}
			set
			{
				if ((this._revenues != value))
				{
					this.OnrevenuesChanging(value);
					this.SendPropertyChanging();
					this._revenues = value;
					this.SendPropertyChanged("revenues");
					this.OnrevenuesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_earnings", DbType="Real")]
		public System.Nullable<float> earnings
		{
			get
			{
				return this._earnings;
			}
			set
			{
				if ((this._earnings != value))
				{
					this.OnearningsChanging(value);
					this.SendPropertyChanging();
					this._earnings = value;
					this.SendPropertyChanged("earnings");
					this.OnearningsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_month", DbType="Int")]
		public System.Nullable<int> month
		{
			get
			{
				return this._month;
			}
			set
			{
				if ((this._month != value))
				{
					this.OnmonthChanging(value);
					this.SendPropertyChanging();
					this._month = value;
					this.SendPropertyChanged("month");
					this.OnmonthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_year", DbType="Int")]
		public System.Nullable<int> year
		{
			get
			{
				return this._year;
			}
			set
			{
				if ((this._year != value))
				{
					this.OnyearChanging(value);
					this.SendPropertyChanging();
					this._year = value;
					this.SendPropertyChanged("year");
					this.OnyearChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
