#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace affsbook
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="adsrush")]
	public partial class OffersDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTable_Affsbook_Offer(Table_Affsbook_Offer instance);
    partial void UpdateTable_Affsbook_Offer(Table_Affsbook_Offer instance);
    partial void DeleteTable_Affsbook_Offer(Table_Affsbook_Offer instance);
    #endregion
		
		public OffersDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["adsrushConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public OffersDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OffersDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OffersDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OffersDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Table_Affsbook_Offer> Table_Affsbook_Offers
		{
			get
			{
				return this.GetTable<Table_Affsbook_Offer>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_Affsbook_Offers")]
	public partial class Table_Affsbook_Offer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<System.DateTime> _date;
		
		private System.Nullable<int> _active;
		
		private System.Nullable<int> _owneraid;
		
		private string _ownerusername;
		
		private string _networkname;
		
		private System.Nullable<int> _networkaid;
		
		private string _title;
		
		private string _commissiontype;
		
		private string _commissions;
		
		private string _description;
		
		private string _niche1;
		
		private string _niche2;
		
		private string _niche3;
		
		private string _subniche;
		
		private string _offerurl;
		
		private string _joinurl;
		
		private string _imageurl;
		
		private System.Nullable<int> _rating;
		
		private string _restrictions;
		
		private System.Nullable<int> _relatedofferid;
		
		private System.Nullable<int> _sponsored;
		
		private System.Nullable<int> _featured;
		
		private System.Nullable<int> _priority;
		
		private System.Nullable<int> _popular;
		
		private string _company;
		
		private string _paymentmethods;
		
		private string _minimumpayout;
		
		private string _shortdescription;
		
		private string _country;
		
		private string _city;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OndateChanging(System.Nullable<System.DateTime> value);
    partial void OndateChanged();
    partial void OnactiveChanging(System.Nullable<int> value);
    partial void OnactiveChanged();
    partial void OnowneraidChanging(System.Nullable<int> value);
    partial void OnowneraidChanged();
    partial void OnownerusernameChanging(string value);
    partial void OnownerusernameChanged();
    partial void OnnetworknameChanging(string value);
    partial void OnnetworknameChanged();
    partial void OnnetworkaidChanging(System.Nullable<int> value);
    partial void OnnetworkaidChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OncommissiontypeChanging(string value);
    partial void OncommissiontypeChanged();
    partial void OncommissionsChanging(string value);
    partial void OncommissionsChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void Onniche1Changing(string value);
    partial void Onniche1Changed();
    partial void Onniche2Changing(string value);
    partial void Onniche2Changed();
    partial void Onniche3Changing(string value);
    partial void Onniche3Changed();
    partial void OnsubnicheChanging(string value);
    partial void OnsubnicheChanged();
    partial void OnofferurlChanging(string value);
    partial void OnofferurlChanged();
    partial void OnjoinurlChanging(string value);
    partial void OnjoinurlChanged();
    partial void OnimageurlChanging(string value);
    partial void OnimageurlChanged();
    partial void OnratingChanging(System.Nullable<int> value);
    partial void OnratingChanged();
    partial void OnrestrictionsChanging(string value);
    partial void OnrestrictionsChanged();
    partial void OnrelatedofferidChanging(System.Nullable<int> value);
    partial void OnrelatedofferidChanged();
    partial void OnsponsoredChanging(System.Nullable<int> value);
    partial void OnsponsoredChanged();
    partial void OnfeaturedChanging(System.Nullable<int> value);
    partial void OnfeaturedChanged();
    partial void OnpriorityChanging(System.Nullable<int> value);
    partial void OnpriorityChanged();
    partial void OnpopularChanging(System.Nullable<int> value);
    partial void OnpopularChanged();
    partial void OncompanyChanging(string value);
    partial void OncompanyChanged();
    partial void OnpaymentmethodsChanging(string value);
    partial void OnpaymentmethodsChanged();
    partial void OnminimumpayoutChanging(string value);
    partial void OnminimumpayoutChanged();
    partial void OnshortdescriptionChanging(string value);
    partial void OnshortdescriptionChanged();
    partial void OncountryChanging(string value);
    partial void OncountryChanged();
    partial void OncityChanging(string value);
    partial void OncityChanged();
    #endregion
		
		public Table_Affsbook_Offer()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_active", DbType="Int")]
		public System.Nullable<int> active
		{
			get
			{
				return this._active;
			}
			set
			{
				if ((this._active != value))
				{
					this.OnactiveChanging(value);
					this.SendPropertyChanging();
					this._active = value;
					this.SendPropertyChanged("active");
					this.OnactiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_owneraid", DbType="Int")]
		public System.Nullable<int> owneraid
		{
			get
			{
				return this._owneraid;
			}
			set
			{
				if ((this._owneraid != value))
				{
					this.OnowneraidChanging(value);
					this.SendPropertyChanging();
					this._owneraid = value;
					this.SendPropertyChanged("owneraid");
					this.OnowneraidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ownerusername", DbType="NVarChar(500)")]
		public string ownerusername
		{
			get
			{
				return this._ownerusername;
			}
			set
			{
				if ((this._ownerusername != value))
				{
					this.OnownerusernameChanging(value);
					this.SendPropertyChanging();
					this._ownerusername = value;
					this.SendPropertyChanged("ownerusername");
					this.OnownerusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_networkname", DbType="NVarChar(500)")]
		public string networkname
		{
			get
			{
				return this._networkname;
			}
			set
			{
				if ((this._networkname != value))
				{
					this.OnnetworknameChanging(value);
					this.SendPropertyChanging();
					this._networkname = value;
					this.SendPropertyChanged("networkname");
					this.OnnetworknameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_networkaid", DbType="Int")]
		public System.Nullable<int> networkaid
		{
			get
			{
				return this._networkaid;
			}
			set
			{
				if ((this._networkaid != value))
				{
					this.OnnetworkaidChanging(value);
					this.SendPropertyChanging();
					this._networkaid = value;
					this.SendPropertyChanged("networkaid");
					this.OnnetworkaidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(1000)")]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_commissiontype", DbType="NVarChar(500)")]
		public string commissiontype
		{
			get
			{
				return this._commissiontype;
			}
			set
			{
				if ((this._commissiontype != value))
				{
					this.OncommissiontypeChanging(value);
					this.SendPropertyChanging();
					this._commissiontype = value;
					this.SendPropertyChanged("commissiontype");
					this.OncommissiontypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_commissions", DbType="NVarChar(4000)")]
		public string commissions
		{
			get
			{
				return this._commissions;
			}
			set
			{
				if ((this._commissions != value))
				{
					this.OncommissionsChanging(value);
					this.SendPropertyChanging();
					this._commissions = value;
					this.SendPropertyChanged("commissions");
					this.OncommissionsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="NVarChar(4000)")]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_niche1", DbType="NVarChar(400)")]
		public string niche1
		{
			get
			{
				return this._niche1;
			}
			set
			{
				if ((this._niche1 != value))
				{
					this.Onniche1Changing(value);
					this.SendPropertyChanging();
					this._niche1 = value;
					this.SendPropertyChanged("niche1");
					this.Onniche1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_niche2", DbType="NVarChar(400)")]
		public string niche2
		{
			get
			{
				return this._niche2;
			}
			set
			{
				if ((this._niche2 != value))
				{
					this.Onniche2Changing(value);
					this.SendPropertyChanging();
					this._niche2 = value;
					this.SendPropertyChanged("niche2");
					this.Onniche2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_niche3", DbType="NChar(400)")]
		public string niche3
		{
			get
			{
				return this._niche3;
			}
			set
			{
				if ((this._niche3 != value))
				{
					this.Onniche3Changing(value);
					this.SendPropertyChanging();
					this._niche3 = value;
					this.SendPropertyChanged("niche3");
					this.Onniche3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subniche", DbType="NVarChar(500)")]
		public string subniche
		{
			get
			{
				return this._subniche;
			}
			set
			{
				if ((this._subniche != value))
				{
					this.OnsubnicheChanging(value);
					this.SendPropertyChanging();
					this._subniche = value;
					this.SendPropertyChanged("subniche");
					this.OnsubnicheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_offerurl", DbType="NVarChar(1500)")]
		public string offerurl
		{
			get
			{
				return this._offerurl;
			}
			set
			{
				if ((this._offerurl != value))
				{
					this.OnofferurlChanging(value);
					this.SendPropertyChanging();
					this._offerurl = value;
					this.SendPropertyChanged("offerurl");
					this.OnofferurlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_joinurl", DbType="NVarChar(1500)")]
		public string joinurl
		{
			get
			{
				return this._joinurl;
			}
			set
			{
				if ((this._joinurl != value))
				{
					this.OnjoinurlChanging(value);
					this.SendPropertyChanging();
					this._joinurl = value;
					this.SendPropertyChanged("joinurl");
					this.OnjoinurlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imageurl", DbType="NVarChar(1500)")]
		public string imageurl
		{
			get
			{
				return this._imageurl;
			}
			set
			{
				if ((this._imageurl != value))
				{
					this.OnimageurlChanging(value);
					this.SendPropertyChanging();
					this._imageurl = value;
					this.SendPropertyChanged("imageurl");
					this.OnimageurlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rating", DbType="Int")]
		public System.Nullable<int> rating
		{
			get
			{
				return this._rating;
			}
			set
			{
				if ((this._rating != value))
				{
					this.OnratingChanging(value);
					this.SendPropertyChanging();
					this._rating = value;
					this.SendPropertyChanged("rating");
					this.OnratingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_restrictions", DbType="NVarChar(4000)")]
		public string restrictions
		{
			get
			{
				return this._restrictions;
			}
			set
			{
				if ((this._restrictions != value))
				{
					this.OnrestrictionsChanging(value);
					this.SendPropertyChanging();
					this._restrictions = value;
					this.SendPropertyChanged("restrictions");
					this.OnrestrictionsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_relatedofferid", DbType="Int")]
		public System.Nullable<int> relatedofferid
		{
			get
			{
				return this._relatedofferid;
			}
			set
			{
				if ((this._relatedofferid != value))
				{
					this.OnrelatedofferidChanging(value);
					this.SendPropertyChanging();
					this._relatedofferid = value;
					this.SendPropertyChanged("relatedofferid");
					this.OnrelatedofferidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sponsored", DbType="Int")]
		public System.Nullable<int> sponsored
		{
			get
			{
				return this._sponsored;
			}
			set
			{
				if ((this._sponsored != value))
				{
					this.OnsponsoredChanging(value);
					this.SendPropertyChanging();
					this._sponsored = value;
					this.SendPropertyChanged("sponsored");
					this.OnsponsoredChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_featured", DbType="Int")]
		public System.Nullable<int> featured
		{
			get
			{
				return this._featured;
			}
			set
			{
				if ((this._featured != value))
				{
					this.OnfeaturedChanging(value);
					this.SendPropertyChanging();
					this._featured = value;
					this.SendPropertyChanged("featured");
					this.OnfeaturedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_priority", DbType="Int")]
		public System.Nullable<int> priority
		{
			get
			{
				return this._priority;
			}
			set
			{
				if ((this._priority != value))
				{
					this.OnpriorityChanging(value);
					this.SendPropertyChanging();
					this._priority = value;
					this.SendPropertyChanged("priority");
					this.OnpriorityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_popular", DbType="Int")]
		public System.Nullable<int> popular
		{
			get
			{
				return this._popular;
			}
			set
			{
				if ((this._popular != value))
				{
					this.OnpopularChanging(value);
					this.SendPropertyChanging();
					this._popular = value;
					this.SendPropertyChanged("popular");
					this.OnpopularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_company", DbType="NVarChar(500)")]
		public string company
		{
			get
			{
				return this._company;
			}
			set
			{
				if ((this._company != value))
				{
					this.OncompanyChanging(value);
					this.SendPropertyChanging();
					this._company = value;
					this.SendPropertyChanged("company");
					this.OncompanyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paymentmethods", DbType="NVarChar(1500)")]
		public string paymentmethods
		{
			get
			{
				return this._paymentmethods;
			}
			set
			{
				if ((this._paymentmethods != value))
				{
					this.OnpaymentmethodsChanging(value);
					this.SendPropertyChanging();
					this._paymentmethods = value;
					this.SendPropertyChanged("paymentmethods");
					this.OnpaymentmethodsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_minimumpayout", DbType="NVarChar(1500)")]
		public string minimumpayout
		{
			get
			{
				return this._minimumpayout;
			}
			set
			{
				if ((this._minimumpayout != value))
				{
					this.OnminimumpayoutChanging(value);
					this.SendPropertyChanging();
					this._minimumpayout = value;
					this.SendPropertyChanged("minimumpayout");
					this.OnminimumpayoutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shortdescription", DbType="NVarChar(650)")]
		public string shortdescription
		{
			get
			{
				return this._shortdescription;
			}
			set
			{
				if ((this._shortdescription != value))
				{
					this.OnshortdescriptionChanging(value);
					this.SendPropertyChanging();
					this._shortdescription = value;
					this.SendPropertyChanged("shortdescription");
					this.OnshortdescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_country", DbType="NVarChar(500)")]
		public string country
		{
			get
			{
				return this._country;
			}
			set
			{
				if ((this._country != value))
				{
					this.OncountryChanging(value);
					this.SendPropertyChanging();
					this._country = value;
					this.SendPropertyChanged("country");
					this.OncountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="NVarChar(500)")]
		public string city
		{
			get
			{
				return this._city;
			}
			set
			{
				if ((this._city != value))
				{
					this.OncityChanging(value);
					this.SendPropertyChanging();
					this._city = value;
					this.SendPropertyChanged("city");
					this.OncityChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
